ALTER TABLE events 
    ADD COLUMN IF NOT EXISTS src_ip TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS src_port INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dst_ip TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS dst_port INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS proto TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_events_src_ip ON events (src_ip);