ALTER TABLE events
    ADD COLUMN IF NOT EXISTS container TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS process   TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS os_user   TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_events_container ON events (container) WHERE container <> '';

ALTER TABLE alerts     ADD COLUMN IF NOT EXISTS link_ip TEXT NOT NULL DEFAULT '';
ALTER TABLE incidents  ADD COLUMN IF NOT EXISTS targets JSONB NOT NULL DEFAULT '[]';